// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Excercise3Section3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Excercise3Section3));
        
        string IMigrationMetadata.Id
        {
            get { return "201811020807374_Excercise3Section3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
